### ISSUE TITLE
Error installing gem

### ISSUE THREAD

**Issue by OliverJAsh** [stereobooster/html_press#1]
Trying to install the html_press gem, I get this error:

```
➜  OliverJAsh  sudo gem install "html_press"
ERROR:  While executing gem ... (NoMethodError)
    undefined method `call' for nil:NilClass
```

**Comment by stereobooster** [comment]
Please provide ruby version (`ruby -v`). tnx

**Comment by OliverJAsh** [comment]
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

**Comment by stereobooster** [comment]
I can reproduce error with following versions

```
ruby -v
ruby 1.8.7 (2011-02-18 patchlevel 334)
gem -v
1.5.2
```

You can update rubygem (`gem update --system`), while I'm trying to find solution.
I believe that updating rubygem will solve your problem.

**Comment by stereobooster** [comment]
Try to install latest version (`0.6.6`). Problem was in gemspec of `csspress` (see [commit](https://github.com/stereobooster/css_press/commit/d2cae3ccc4413d3b6ff3cbf109d2ed38c3b94fb6#L0R21))

**Comment by OliverJAsh** [comment]
That works. Thank you.
