### ISSUE TITLE
Incorrect rem formatting

### ISSUE THREAD

**Issue by Eelviny** [stereobooster/html_press#16]
Take this bit of example code:
`<div style="padding:2rem;"></div>`

html_press transforms this into:
`<div style="padding:2 rem"></div>`

This breaks the website rendering of this padding element, as a space is put in between the "2" and the "rem". This means I can't use rem units inline with my HTML.
_I use [Octopress minify HTML plugin](https://github.com/octopress/minify-html), which uses this gem. Apologies if this doesn't directly affect html_press, I just thought this to most likely be an upstream issue!_

**Comment by Eun** [comment]
Same here

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/html_press/issues/21
