### ISSUE TITLE
Parsing issue

### ISSUE THREAD

**Issue by joeworkman** [stereobooster/html_press#3]
The following does not get minified properly.

```
<li data-location="<b>Location</b>"></li>
```

An extra space is getting inserted into the first bold tag... 

```
<li data-location='< b>Location</b>'></li>
```

**Comment by stereobooster** [comment]
Not sure if this is valid markup.
html validator says: "Unescaped '<' not allowed in attributes values"

**Comment by stereobooster** [comment]
My recommendation use html entities instead of `<` and `>` in attributes values.
Closing it for now.

**Comment by joeworkman** [comment]
Thanks. 

## 

Cheers,
Joe
