### ISSUE TITLE
Preserving whitespace

### ISSUE THREAD

**Issue by mneumegen** [stereobooster/html_press#4]
I've had some unexpected behaviour minifying an unordered list. Let's say you have the following HTML:

`<html>
  <body>
    <ul> <li style="display:inline">Item 1</li> <li style="display:inline">Item 2</li> </ul>
  </body>
</html>`

This will display as:
Item 1 Item2

After being minimized using html_press it changes to:
Item1Item2

I'm trying to find the balance between rendering the original HTML file vs squeezing out minimal HTML. In my case I've forked html_press and commented out process_block_elements.

From the library's point of view it's not clear if you can make the same decision because whitespace should have no effect block level elements unless you mess with them in CSS. 

It's something for you to ponder anyway.

**Comment by stereobooster** [comment]
If you're displaying the `<li>` elements inline (to create a horizontal menu) the line-breaks between the sibling `<li>`s are being converted into a single white-space.

Good practice to remove whitespaces and control visual appearance with css (`margin-left:10px`). It will be more consistent and crossbrowser solution.

If you want to customize list of block ellements you can do it [here](https://github.com/stereobooster/html_press/blob/master/lib/html_press/html.rb#L124)

**Comment by mneumegen** [comment]
Yip, totally agree on using margins instead of spaces. Unfortunately, my users are writing the HTML and expect their HTML to work exactly as they wrote it. So I'm wanting a "safe" compression.

Even with margins, you could potentially have the same problem: 

`<ul><li style="display:inline; margin-right:10px">Item 1</li> <li style="display:inline">Item 2</li></ul>`

and

`<ul><li style="display:inline; margin-right: 10px">Item 1</li><li style="display:inline">Item 2</li></ul>`

will have different spacing.

You've done an amazing job with html_press and saved me a whole lot of work. This is the only thing that doesn't work for me (and commenting out the call process_block_elements fixes my problem).

**Comment by stereobooster** [comment]
it is well known problem. People fixing it like so:

``` html
...<li>element One</li><!--
--><li>element Two</li><!--
--><li>element Three</li>...
```

or:

``` html
...<li>element One</li
   ><li>element Two</li
   ><li>element Three</li>...
```

But Im not faced this problem for a long time. Is it ie6/7 bug?

**Comment by stereobooster** [comment]
> This is the only thing that doesn't work for me (and commenting out the call process_block_elements fixes my problem).

Change [list of block ellements](https://github.com/stereobooster/html_press/blob/master/lib/html_press/html.rb#L124) instead (remove `li`).

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/html_press/issues/21
