### ISSUE TITLE
Invalid option: inline_script

### ISSUE THREAD

**Issue by RoxasShadow** [stereobooster/html_press#6]
If in my view there is a `<script>` tag, it brokes html_press.

`ArgumentError at /
Invalid option: inline_script
file: uglifier.rb
location: initialize
line: 86
`

**Comment by stereobooster** [comment]
What version of uglifier do you use?

**Comment by RoxasShadow** [comment]
The latest. I do 'bundle install' to a Gemfile containing execjs, therubyracer and html_press with the source sets to rubygems.org
