### ISSUE TITLE
Rack Middleware

### ISSUE THREAD

**Issue by wbotelhos** [stereobooster/html_press#8]
Hi,

I created a Rack middleware (https://github.com/wbotelhos/html_compress) to automatically compress the html page in a Rails application. I still need to write some tests, but I'm using it and working well.

Maybe it can enter on your Rails usage section. (:

It is working here: http://estacione.com

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/html_press/issues/21
