### ISSUE TITLE
The script removes the break/empty line from textarea

### ISSUE THREAD

**Issue by wbotelhos** [stereobooster/html_press#9]
When we break lines into textarea we want it comes back on edition, but it is cleaned, putting all code together.

The right:

```
------------------------------------------
I jumped one

Line
------------------------------------------
```

The wrong and actual:

```
------------------------------------------
I jumped one
Line
------------------------------------------
```

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/html_press/issues/21
